version: '3.8'

services: 
  php-apache-environment:
    container_name: php-apache
    build: 
      context: ./php
      dockerfile: Dockerfile
    ports: 
      - 8000:80
    volumes:
      - ./php/src:/var/www/html/


